import { Dimensions, StyleSheet } from 'react-native';

const colors = {
    background: '#DEE6F2',
    text: '#3E3E3E',
    text_input: '#CCD8EB',
    subtext: '#3C6DFF',
    icon: '#3E84FE',
    disabled_icon: '#707070ff',
    third_party_auth: '#88B2F9',
    button: '#B1CCFA',
    sign_out: '#FF4646',
    shadow: '#000000',
}

export const styles = StyleSheet.create({
  auth_container: {
    width: Dimensions.get('window').width,
    height: Dimensions.get('window').height,
    backgroundColor: colors.background,
    color: colors.text,
    justifyContent: 'center',
    alignItems: 'center',
    gap: 16,
    flexDirection: 'column',
  },
  auth_buttons_container_vertical: {
    flexDirection: 'column',
    gap: 40,
  },
  auth_buttons_container_horizontal: {
    flexDirection: 'row',
    gap: 40,
  },
  main_container: {
    width: Dimensions.get('window').width,
    height: Dimensions.get('window').height,
    backgroundColor: colors.background,
    paddingHorizontal: 36,
    paddingVertical: 32,
    color: colors.text,
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
    gap: 16,
    flexDirection: 'column',
  },
  top_container: {
    width: '100%',
    justifyContent: 'space-between',
    flexDirection: 'row',
  },
  profile_settings_container: {
    width: 100,
    paddingTop: 20,
    justifyContent: 'space-between',
    alignItems: 'center',
    flexDirection: 'row',
  },
  profile_container: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 4,
  },
  scroll_container: {
    width: '100%',
    height: '100%',
    backgroundColor: colors.background,
    padding: 0,
    gap: 12,
    flexDirection: 'column',
  },
  preview_container: {
    width: '100%',
    backgroundColor: colors.background,
    paddingTop: 8,
    paddingBottom: 16,
    color: colors.text,
    justifyContent: 'center',
    alignItems: 'flex-start',
    gap: 2,
    flexDirection: 'column',
  },
  bottom_container: {
    width: '100%',
    height: 48,
    paddingHorizontal: 24,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
  },
  reply_container: {
    width: '100%',
    height: 48,
    paddingHorizontal: 24,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    backgroundColor: colors.button,
    borderRadius: 20,
  },
  modal_overlay: {
    width: Dimensions.get('window').width,
    height: Dimensions.get('window').height,
    backgroundColor: colors.background,
    justifyContent: 'center',
    alignItems: 'center',
  },
  modal_container: {
    width: 240,
    flexDirection: 'column',
    gap: 4,
    backgroundColor: colors.button,
    borderRadius: 8,
    marginBottom: 24,
  },
  modal_buttons_container: {
    flexDirection: 'row',
    gap: 4,
    justifyContent: 'space-around',
    backgroundColor: colors.button,
    borderRadius: 8,
    paddingBottom: 4,
  },
  h1: {
    fontFamily: 'KaiseiHarunoUmi_400Regular',
    fontSize: 24,
    color: colors.text,
    paddingTop: 24,
    lineHeight: 35,
    textAlign: 'center',
  },
  h2: {
    fontFamily: 'KaiseiHarunoUmi_400Regular',
    fontSize: 16,
    color: colors.text,
    lineHeight: 23,
  },
  user_text: {
    fontFamily: 'SortsMillGoudy_400Regular',
    fontSize: 14,
    color: colors.text,
    lineHeight: 20,
    backgroundColor: colors.text_input,
    paddingHorizontal: 4,
    paddingTop: 4,
    paddingBottom: 4,
  },
  ai_text: {
    fontFamily: 'SortsMillGoudy_400Regular',
    fontSize: 14,
    color: colors.text,
    lineHeight: 20,
    paddingHorizontal: 4,
    paddingTop: 6,
    paddingBottom: 4,
  },
  subtext: {
    fontFamily: 'Raleway_400Regular',
    fontSize: 12,
    color: colors.subtext,
    lineHeight: 14,
  },
  username_input: { 
    backgroundColor: colors.text_input,
    padding: 4,
    width: Dimensions.get('window').width - 72,
    borderRadius: 4,
    fontFamily: 'Raleway_400Regular',
    fontSize: 16,
    color: colors.text,
    lineHeight: 19,
  },
  email_input: { 
    backgroundColor: colors.text_input,
    padding: 4,
    width: Dimensions.get('window').width - 72,
    borderRadius: 4,
    fontFamily: 'Raleway_400Regular',
    fontSize: 16,
    color: colors.text,
    lineHeight: 19,
  },
  password_input: { 
    backgroundColor: colors.text_input,
    padding: 4, 
    width: Dimensions.get('window').width - 72,
    gap: 10,
    borderRadius: 4,
    fontFamily: 'Raleway_400Regular',
    fontSize: 16,
    color: colors.text,
    lineHeight: 19,
  },
  password: {
    width: Dimensions.get('window').width - 72,
    gap: 2,
  },
  auth_button: {
    height: 28,
    paddingHorizontal: 16,
    margin: 16,
    borderRadius: 8, 
    backgroundColor: colors.button, 
    justifyContent: 'center',
    alignItems: 'center',
  },
  auth_button_text: {
    fontFamily: 'Raleway_400Regular',
    fontSize: 16,
    color: colors.text,
    lineHeight: 19,
    textAlign: 'center',
  },
  third_party_auth: {
    paddingVertical: 36,
    gap: 24,
  },
  third_party_auth_button: {
    width: Dimensions.get('window').width - 72,
    height: 32,
    borderRadius: 8, 
    backgroundColor: colors.third_party_auth, 
    justifyContent: 'center',
    alignItems: 'center',
  },
  third_party_auth_button_text: {
    fontFamily: 'Raleway_400Regular',
    fontSize: 16,
    color: colors.text,
    lineHeight: 19,
    textAlign: 'center',
  },
  new_chat_icon: {
    color: colors.icon,
  },
  send_icon: {
    color: colors.icon,
  },
  send_icon_disabled: {
    color: colors.disabled_icon,
  },
  chat_input: {
    width: '100%',
    fontFamily: 'Raleway_400Regular',
    fontSize: 16,
    color: colors.text,
    lineHeight: 19,
    backgroundColor: colors.button,
  },
  profile_icon: {
    color: colors.text,
  },
  log_out_icon: {
    color: colors.sign_out,
  },
  message_menu: {
    width: 100,
    height: 56,
    padding: 8,
    backgroundColor: colors.button,
    gap: 8,
    borderRadius: 8,
    elevation: 8, 
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
  },
  menu_options_text: {
    fontFamily: 'SortsMillGoudy_400Regular',
    fontSize: 14,
    color: colors.text,
    lineHeight: 20,
  },
  modal_text: {
    fontFamily: 'Raleway_400Regular',
    fontSize: 16,
    color: colors.text,
    lineHeight: 19,
    backgroundColor: colors.text_input,
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
  },
  modal_buttons_text: {
    fontFamily: 'Raleway_400Regular',
    fontSize: 16,
    color: colors.text,
    lineHeight: 19,
    textAlign: 'center',
  }
})